version: "2"

services:
  api:
    image: golang:1.8
    restart: on-failure
    volumes:
      - ./cmd/api:/go/src/github.com/dung13890/micro-go/cmd/api
    working_dir: /go/src/github.com/dung13890/micro-go/cmd/api
    environment:
      - GOBIN=/go/bin
    links:
      - user
    ports:
      - "3000:3000"
    tty: true
  user:
    image: golang:1.8
    restart: on-failure
    volumes:
      - ./cmd/user:/go/src/github.com/dung13890/micro-go/cmd/user
    working_dir: /go/src/github.com/dung13890/micro-go/cmd/user
    environment:
      - GOBIN=/go/bin
    tty: true
  caddy:
    image: abiosoft/caddy
    restart: always
    volumes:
     - ./caddyfile:/srv
    ports:
     - "80:80"
     - "443:443"
    links:
      - api
    tty: true
  mongodb:
    image: mongo
    restart: on-failure
    volumes:
      - ./mongodb:/data/db
    tty: true
