// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

/*
Package user is a generated protocol buffer package.

It is generated from these files:
	user.proto

It has these top-level messages:
	Model
	GetRequest
	FindRequest
	CreateRequest
	GetResponse
	FindResponse
	CreateResponse
*/
package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Model struct {
	Id      string           `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name    string           `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Email   string           `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Phone   string           `protobuf:"bytes,4,opt,name=phone" json:"phone,omitempty"`
	Address []*Model_Address `protobuf:"bytes,5,rep,name=address" json:"address,omitempty"`
}

func (m *Model) Reset()                    { *m = Model{} }
func (m *Model) String() string            { return proto.CompactTextString(m) }
func (*Model) ProtoMessage()               {}
func (*Model) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Model) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Model) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Model) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Model) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Model) GetAddress() []*Model_Address {
	if m != nil {
		return m.Address
	}
	return nil
}

type Model_Address struct {
	Street  string `protobuf:"bytes,1,opt,name=street" json:"street,omitempty"`
	City    string `protobuf:"bytes,2,opt,name=city" json:"city,omitempty"`
	State   string `protobuf:"bytes,3,opt,name=state" json:"state,omitempty"`
	Country string `protobuf:"bytes,4,opt,name=country" json:"country,omitempty"`
}

func (m *Model_Address) Reset()                    { *m = Model_Address{} }
func (m *Model_Address) String() string            { return proto.CompactTextString(m) }
func (*Model_Address) ProtoMessage()               {}
func (*Model_Address) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Model_Address) GetStreet() string {
	if m != nil {
		return m.Street
	}
	return ""
}

func (m *Model_Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Model_Address) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Model_Address) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

type GetRequest struct {
	Keyword string `protobuf:"bytes,1,opt,name=keyword" json:"keyword,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetRequest) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

type FindRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *FindRequest) Reset()                    { *m = FindRequest{} }
func (m *FindRequest) String() string            { return proto.CompactTextString(m) }
func (*FindRequest) ProtoMessage()               {}
func (*FindRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *FindRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CreateRequest struct {
	User *Model `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CreateRequest) GetUser() *Model {
	if m != nil {
		return m.User
	}
	return nil
}

type GetResponse struct {
	Status string   `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Users  []*Model `protobuf:"bytes,2,rep,name=users" json:"users,omitempty"`
}

func (m *GetResponse) Reset()                    { *m = GetResponse{} }
func (m *GetResponse) String() string            { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()               {}
func (*GetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *GetResponse) GetUsers() []*Model {
	if m != nil {
		return m.Users
	}
	return nil
}

type FindResponse struct {
	Status string `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	User   *Model `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
}

func (m *FindResponse) Reset()                    { *m = FindResponse{} }
func (m *FindResponse) String() string            { return proto.CompactTextString(m) }
func (*FindResponse) ProtoMessage()               {}
func (*FindResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *FindResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *FindResponse) GetUser() *Model {
	if m != nil {
		return m.User
	}
	return nil
}

type CreateResponse struct {
	Status  string `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CreateResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *CreateResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Model)(nil), "user.Model")
	proto.RegisterType((*Model_Address)(nil), "user.Model.Address")
	proto.RegisterType((*GetRequest)(nil), "user.GetRequest")
	proto.RegisterType((*FindRequest)(nil), "user.FindRequest")
	proto.RegisterType((*CreateRequest)(nil), "user.CreateRequest")
	proto.RegisterType((*GetResponse)(nil), "user.GetResponse")
	proto.RegisterType((*FindResponse)(nil), "user.FindResponse")
	proto.RegisterType((*CreateResponse)(nil), "user.CreateResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for User service

type UserClient interface {
	GetUsers(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	FindUser(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindResponse, error)
	CreateUser(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) GetUsers(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := grpc.Invoke(ctx, "/user.User/GetUsers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) FindUser(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindResponse, error) {
	out := new(FindResponse)
	err := grpc.Invoke(ctx, "/user.User/FindUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) CreateUser(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := grpc.Invoke(ctx, "/user.User/CreateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for User service

type UserServer interface {
	GetUsers(context.Context, *GetRequest) (*GetResponse, error)
	FindUser(context.Context, *FindRequest) (*FindResponse, error)
	CreateUser(context.Context, *CreateRequest) (*CreateResponse, error)
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/GetUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUsers(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_FindUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).FindUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/FindUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).FindUser(ctx, req.(*FindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).CreateUser(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUsers",
			Handler:    _User_GetUsers_Handler,
		},
		{
			MethodName: "FindUser",
			Handler:    _User_FindUser_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _User_CreateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}

func init() { proto.RegisterFile("user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 374 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xc1, 0x4e, 0xe3, 0x30,
	0x10, 0x55, 0xd2, 0xa4, 0xe9, 0x4e, 0x76, 0xab, 0x5d, 0x6f, 0x85, 0xac, 0x48, 0x88, 0x92, 0x03,
	0xea, 0x85, 0x02, 0xe5, 0xc0, 0x19, 0x90, 0x28, 0x17, 0x2e, 0x91, 0xf8, 0x80, 0xd0, 0x8c, 0x20,
	0xa2, 0x8d, 0x8b, 0xed, 0x08, 0xf5, 0x7b, 0xf8, 0x3e, 0xfe, 0x01, 0x79, 0x6c, 0xab, 0x29, 0x12,
	0xea, 0x6d, 0xde, 0xf3, 0x8c, 0xe7, 0xbd, 0x67, 0x03, 0xb4, 0x0a, 0xe5, 0x74, 0x2d, 0x85, 0x16,
	0x2c, 0x32, 0x75, 0xfe, 0x19, 0x40, 0xfc, 0x20, 0x2a, 0x5c, 0xb2, 0x21, 0x84, 0x75, 0xc5, 0x83,
	0x71, 0x30, 0xf9, 0x55, 0x84, 0x75, 0xc5, 0x18, 0x44, 0x4d, 0xb9, 0x42, 0x1e, 0x12, 0x43, 0x35,
	0x1b, 0x41, 0x8c, 0xab, 0xb2, 0x5e, 0xf2, 0x1e, 0x91, 0x16, 0x18, 0x76, 0xfd, 0x22, 0x1a, 0xe4,
	0x91, 0x65, 0x09, 0xb0, 0x53, 0x48, 0xca, 0xaa, 0x92, 0xa8, 0x14, 0x8f, 0xc7, 0xbd, 0x49, 0x3a,
	0xfb, 0x3f, 0xa5, 0xed, 0xb4, 0x6d, 0x7a, 0x6d, 0x8f, 0x0a, 0xdf, 0x93, 0x21, 0x24, 0x8e, 0x63,
	0x07, 0xd0, 0x57, 0x5a, 0x22, 0x6a, 0xa7, 0xc6, 0x21, 0xa3, 0x68, 0x51, 0xeb, 0x8d, 0x57, 0x64,
	0x6a, 0xb3, 0x5b, 0xe9, 0x52, 0xa3, 0x57, 0x44, 0x80, 0x71, 0x48, 0x16, 0xa2, 0x6d, 0xb4, 0xdc,
	0x38, 0x4d, 0x1e, 0xe6, 0x27, 0x00, 0x73, 0xd4, 0x05, 0xbe, 0xb5, 0xa8, 0xb4, 0xe9, 0x7b, 0xc5,
	0xcd, 0xbb, 0x90, 0xde, 0xb8, 0x87, 0xf9, 0x21, 0xa4, 0x77, 0x75, 0x53, 0xf9, 0xc6, 0x6f, 0xe1,
	0xe4, 0xe7, 0xf0, 0xe7, 0x56, 0x62, 0xa9, 0xd1, 0x37, 0x1c, 0x01, 0xe5, 0x49, 0x2d, 0xe9, 0x2c,
	0xed, 0x58, 0x2d, 0x6c, 0xd0, 0xf7, 0x90, 0xd2, 0x62, 0xb5, 0x16, 0x8d, 0x42, 0xeb, 0xb1, 0xd4,
	0xad, 0xda, 0x7a, 0x34, 0x88, 0x1d, 0x43, 0x6c, 0xda, 0x15, 0x0f, 0x29, 0xb3, 0x9d, 0x8b, 0xec,
	0x49, 0x3e, 0x87, 0xdf, 0x56, 0xda, 0x9e, 0xab, 0xbc, 0xa4, 0xf0, 0x27, 0x49, 0x37, 0x30, 0xf4,
	0x26, 0xf6, 0x5c, 0xc5, 0x21, 0x59, 0xa1, 0x52, 0xe5, 0xb3, 0xff, 0x0e, 0x1e, 0xce, 0x3e, 0x02,
	0x88, 0x1e, 0x15, 0x4a, 0x76, 0x06, 0x83, 0x39, 0x6a, 0x53, 0x2a, 0xf6, 0xd7, 0xee, 0xda, 0x06,
	0x9d, 0xfd, 0xeb, 0x30, 0x6e, 0xd7, 0x05, 0x0c, 0x8c, 0x0d, 0x1a, 0x76, 0xc7, 0x9d, 0xc4, 0x33,
	0xd6, 0xa5, 0xdc, 0xc8, 0x15, 0x80, 0x15, 0x4c, 0x43, 0xee, 0x3f, 0xed, 0xbc, 0x43, 0x36, 0xda,
	0x25, 0xed, 0xe0, 0x53, 0x9f, 0xbe, 0xfc, 0xe5, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x39, 0xab,
	0xa3, 0xa0, 0x00, 0x03, 0x00, 0x00,
}
